// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.Models;

#nullable disable

namespace Shop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shop.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeptId")
                        .HasColumnType("int");

                    b.Property<int>("Drgree")
                        .HasColumnType("int");

                    b.Property<int>("MinDrgree")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeptId");

                    b.ToTable("Course");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeptId = 1,
                            Drgree = 100,
                            MinDrgree = 50,
                            Name = "Introduction to Programming"
                        },
                        new
                        {
                            Id = 2,
                            DeptId = 1,
                            Drgree = 100,
                            MinDrgree = 60,
                            Name = "Database Design"
                        },
                        new
                        {
                            Id = 3,
                            DeptId = 2,
                            Drgree = 100,
                            MinDrgree = 55,
                            Name = "Web Development"
                        },
                        new
                        {
                            Id = 4,
                            DeptId = 3,
                            Drgree = 100,
                            MinDrgree = 65,
                            Name = "Software Architecture"
                        });
                });

            modelBuilder.Entity("Shop.Models.CrsDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Crs_Id")
                        .HasColumnType("int");

                    b.Property<int>("Degree")
                        .HasColumnType("int");

                    b.Property<int>("TraineeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Crs_Id");

                    b.HasIndex("TraineeId");

                    b.ToTable("CrsDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Crs_Id = 1,
                            Degree = 85,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Crs_Id = 2,
                            Degree = 92,
                            TraineeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Crs_Id = 3,
                            Degree = 78,
                            TraineeId = 3
                        });
                });

            modelBuilder.Entity("Shop.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ManagerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ManagerName = "John Smith",
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = 2,
                            ManagerName = "Sarah Johnson",
                            Name = "Information Systems"
                        },
                        new
                        {
                            Id = 3,
                            ManagerName = "Michael Brown",
                            Name = "Software Engineering"
                        });
                });

            modelBuilder.Entity("Shop.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CrsId")
                        .HasColumnType("int");

                    b.Property<int>("DeptId")
                        .HasColumnType("int");

                    b.Property<string>("ImgURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CrsId");

                    b.HasIndex("DeptId");

                    b.ToTable("Instructor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "321 Faculty Lane",
                            CrsId = 1,
                            DeptId = 1,
                            ImgURL = "/images/instructors/robert.jpg",
                            Name = "Dr. Robert Wilson",
                            Salary = 75000
                        },
                        new
                        {
                            Id = 2,
                            Address = "654 Professor Ave",
                            CrsId = 2,
                            DeptId = 2,
                            ImgURL = "/images/instructors/lisa.jpg",
                            Name = "Prof. Lisa Anderson",
                            Salary = 80000
                        },
                        new
                        {
                            Id = 3,
                            Address = "987 Teacher St",
                            CrsId = 3,
                            DeptId = 3,
                            ImgURL = "/images/instructors/david.jpg",
                            Name = "Dr. David Thompson",
                            Salary = 72000
                        });
                });

            modelBuilder.Entity("Shop.Models.Trainee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeptId")
                        .HasColumnType("int");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeptId");

                    b.ToTable("Trainee");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Student St",
                            DeptId = 1,
                            Grade = "A",
                            ImgURL = "/images/trainees/alex.jpg",
                            Name = "Alex Wilson"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 College Ave",
                            DeptId = 2,
                            Grade = "B+",
                            ImgURL = "/images/trainees/emma.jpg",
                            Name = "Emma Davis"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 University Blvd",
                            DeptId = 3,
                            Grade = "A-",
                            ImgURL = "/images/trainees/james.jpg",
                            Name = "James Miller"
                        });
                });

            modelBuilder.Entity("Shop.Models.Course", b =>
                {
                    b.HasOne("Shop.Models.Department", "Department")
                        .WithMany("Course")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Shop.Models.CrsDetails", b =>
                {
                    b.HasOne("Shop.Models.Course", "Course")
                        .WithMany("CrsDetails")
                        .HasForeignKey("Crs_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop.Models.Trainee", "Trainee")
                        .WithMany("CrsDetails")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("Shop.Models.Instructor", b =>
                {
                    b.HasOne("Shop.Models.Course", "Course")
                        .WithMany("Instructor")
                        .HasForeignKey("CrsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop.Models.Department", "Department")
                        .WithMany("Instructor")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Shop.Models.Trainee", b =>
                {
                    b.HasOne("Shop.Models.Department", "Department")
                        .WithMany("Trainee")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Shop.Models.Course", b =>
                {
                    b.Navigation("CrsDetails");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("Shop.Models.Department", b =>
                {
                    b.Navigation("Course");

                    b.Navigation("Instructor");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("Shop.Models.Trainee", b =>
                {
                    b.Navigation("CrsDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
